### ISSUE TITLE
편집한 동영상 처리 및 저장 방식

### ISSUE THREAD

**Issue by joh16** [boostcamp-2020/Project13-Web-Video-Editor#71]
# 원본 동영상 파일 + 필터 상태

## 개요
원본 동영상 파일과 WebGL을 통해 적용하고 있는 필터 상태를 함께 저장합니다.

## 요구사항
  - 필터 상태는 큰 딜레이 없이, 순수하게 WebGL로 불러올 수 있어야 합니다.
  - 편집된 동영상을 재생할 수 있는 뷰어를 구현해야 합니다.

## 문제점
  - 동영상 플레이어에서 재생할 수 없습니다.
  - 뷰어 구현, 최적화에 상당한 시간이 소요될 수 있습니다.

# ffmpeg.wasm을 이용하여 mp4와 같은 (컨테이너) 파일로 저장

## 개요
Web Assembly를 통해 기존 라이브러리인 ffmpeg를 사용하여 인코딩을 수행합니다.

## 요구사항
  - 결과물 파일을 서버에 업로드하고, 사용자가 다운로드 할 수 있어야 합니다.
  - 결과물 파일에 편집이 적용되어 있어야 합니다.

## 문제점
  - 현재 편집을 적용하여 인코딩을 한 사례는 확인되지 않았습니다.
  - [한 repo](https://github.com/mattdesl/mp4-wasm-encoder)의 [데모](https://mattdesl.github.io/mp4-wasm-encoder/)에 따르면 편집도 안 하는데 영상 길이보다 인코딩 시간이 오래 걸립니다.

# Web Codecs를 이용하여 mp4와 같은 (컨테이너) 파일로 저장

## 개요
Web Codecs를 통해 동영상을 재생하며 프레임을 받아오고, 이 프레임을 ImageBitmap을 거쳐 WebGL canvas상에서 편집한 후, 이를 인코딩합니다.

## 요구사항
  - Web Codecs 스펙 상 오디오 인코딩이 지원되나, 현재 미구현인 상태입니다. 따라서, 별도 라이브러리를 사용하여 영상에서 오디오 트랙만 추출해야 합니다.
  - mux.js 등의 라이브러리를 활용하여 EncodedVideoChunk(encoded frame + timestamp)와 별도로 추출한 오디오 트랙을 합쳐서 컨테이너 파일로 저장해야 합니다. 이 때, 오디오 트랙과 비디오 트랙의 싱크가 맞아야 합니다.

## 문제점
  - MediaStreamTrack에서 Frame을 받아오는 VideoTrackReader가 브라우저 및 하드웨어 상황에 따라 30FPS를 유지하지 못하고 불규칙하게 프레임 드랍이 일어나는 현상이 있습니다. 최적화로 문제가 해결되지 않을 경우, 유동 또는 낮은 FPS로 비디오를 저장해야합니다. 이것마저 불가능하다면, EncodedVideoChunk를 재생하는 별도 뷰어를 만들어야 합니다.
  - 실험 중인 기술이기 때문에 token을 발급받아야 사용이 가능하며, 추후 지원이 중단될 수 있습니다. 또한, 문서와 예시 코드가 부실한 편이어서 문제 발생 시 해결이 어렵습니다.

**Comment by sculove** [comment]
ffmpeg.wasm을 이용하여 mp4와 같은 (컨테이너) 파일로 저장 방식과 Web Codecs를 이용하여 mp4와 같은 (컨테이너) 파일로 저장
방식은 사실상 같습니다.

인코딩을 Web Codecs을 쓰느냐? 아니면 ffmpeg.wasm을 쓰느냐인데요.
ffmpeg.wasm은 Bitmap정보들의 frame을 인코딩하는게 전부이고 그 Bitmap정보는 canvas에서 추출되기 때문에 편집은 가능하겠죠?

현재 기술성숙도로봤을때  Web Codecs은 전 회의때 언급한것처럼 실서비스로 만들기는 어려울것 같아요.

ffmpeg.wasm의 문제는 **속도 이슈**인데요.
공유 드린 데모는 worker가 1개입니다. **이걸 여러 개로 나눠서 하면 개선될수 있을지가 관건입니다.**

그럼 현실적으로 보면
"원본 동영상 파일 + 필터 상태" 와 "ffmpeg.wasm을 이용하여 mp4와 같은 (컨테이너) 파일로 저장"
2개 방식 중에 선택을 하면 될것 같습니다.

기간이 얼마 남지 않은 상태에서 적합한 방식은 
"원본 동영상 파일 + 필터 상태" 안 인것 같고 가능하다면 "ffmpeg.wasm을 이용하여 mp4와 같은 (컨테이너) 파일로 저장"을 해보면 좋을것 같습니다.

**Comment by joh16** [comment]
ffmpeg.wasm을 이용하여 구현 완료
